### PR TITLE
Added example with custom headers

### PR DESCRIPTION
**Pull request by yomed**
Per #12 - I tried to follow your style, let me know if you had something different in mind.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
👍 Perfect! ✨ 

Thanks a lot! 🍰

PS: Editing the README.md manually is not required, because these files are generated (across my repos). 😜

**Comment by yomed** [comment]
Hey @IonicaBizau - do you have happen to have any docs/info on how you setup the updates across all your repos?

**Comment by IonicaBizau** [comment]
@yomed I will write a blog post about that, soon. 📝

**Comment by yomed** [comment]
Great! I'll keep an eye out for it.

**Pull request merged**
